apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: khaled55/proxy:latest
        imagePullPolicy: Never
        
        
        ports:
        - containerPort: 443